name: urbandelive
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  extended_phone_number_input: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - /Users/ishajasani/Desktop/UrbanDeliv/urbandelive_frontend/assets/Carrier.png
    - /Users/ishajasani/Desktop/UrbanDeliv/urbandelive_frontend/assets/Logo.png