name: urbandelive
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  extended_phone_number_input: ^1.0.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  http: ^0.13.6
  cloud_firestore: ^4.7.1
  country_picker: ^2.0.20
  firebase_storage: ^11.2.1
  pinput: ^2.2.16
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Carrier.png
    - assets/Logo.png