# Generated by Django 4.2 on 2023-05-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("businessName", models.CharField(max_length=25, unique=True)),
                (
                    "businessNameSlug",
                    models.CharField(max_length=25, null=True, unique=True),
                ),
                ("isActive", models.BooleanField(default=False)),
                ("contactNo", models.IntegerField()),
                ("businessCategory", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=25)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="blank-profile-picture.png",
                        upload_to="item_image",
                    ),
                ),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True,
                        default="Hey there, I am using Urban Deliv !!!",
                        max_length=100,
                    ),
                ),
                (
                    "isBusiness",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.business",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=25)),
                ("categoryType", models.CharField(max_length=25)),
                ("items", models.ManyToManyField(blank=True, to="backend.item")),
            ],
        ),
        migrations.AddField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(blank=True, to="backend.category"),
        ),
    ]
