# Generated by Django 4.2 on 2023-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(default="2023-05-23 10:02:14"),
        ),
    ]
