# Generated by Django 4.2 on 2023-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="businessLogo",
            field=models.ImageField(
                blank=True,
                default="blank-profile-picture.png",
                upload_to="businessLogo",
            ),
        ),
    ]
