# Generated by Django 4.2 on 2023-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_business_businesslogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="categoryImage",
            field=models.ImageField(
                blank=True,
                default="blank-profile-picture.png",
                upload_to="categoryImage",
            ),
        ),
    ]
