# Generated by Django 4.2 on 2023-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_business_categoryimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="categoryImage",
        ),
        migrations.AddField(
            model_name="category",
            name="categoryImage",
            field=models.ImageField(
                blank=True,
                default="blank-profile-picture.png",
                upload_to="categoryImage",
            ),
        ),
    ]
